version: '3'
services:
  edutask-db:
    image: postgres:13
    environment:
      POSTGRES_DB: edutask
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8081:8080"
  edutask-app:
    build: .
    ports:
      - "8080:8080"
